# Generated by Django 6.1 on 2026-08-27 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('couleur', models.CharField(default='#000000', help_text='Code couleur hexadécimal', max_length=20)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='faible', max_length=10)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demandes.categorie')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demandes.statut')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='demandes.demande')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ancien_statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='demandes.statut')),
                ('nouveau_statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='demandes.statut')),
            ],
        ),
    ]
