# Generated by Django 6.1 on 2026-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='categorie',
        ),
        migrations.AddField(
            model_name='demande',
            name='type_intervention',
            field=models.CharField(choices=[('materiel', 'Matériel'), ('reseau', 'Réseau/Logiciel'), ('logistique', 'Logistique')], default='materiel', max_length=20),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
