# Generated by Django 6.1 on 2026-08-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='commentaire',
            field=models.TextField(),
        ),
    ]
