# Generated by Django 6.1 on 2026-09-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscaladeExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prestataire', models.CharField(max_length=150)),
                ('contact_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_externe', models.CharField(blank=True, help_text='N° ticket externe / RMA', max_length=100, null=True)),
                ('motif', models.TextField(help_text='Raison du recours au prestataire')),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('en_attente_devis', 'En attente de devis'), ('en_cours_reparation', 'En cours de réparation / SAV'), ('en_attente_livraison', 'En attente de pièces / livraison'), ('repare_retourne', 'Réparé & retourné aux locaux'), ('annule', 'Annulé')], default='en_attente_devis', max_length=30)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_retour_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_retour_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalades_externes', to='demandes.demande')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EchangeExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echange', models.CharField(choices=[('email', 'Email'), ('appel', 'Appel téléphonique'), ('devis', 'Devis / Facturation'), ('expedition', 'Expédition / Réception'), ('note', 'Note interne SAV')], default='email', max_length=30)),
                ('sujet', models.CharField(blank=True, max_length=200, null=True)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('escalade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='interventions.escaladeexterne')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
